# Generated by Django 3.2.9 on 2021-11-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscribes',
            table='user_subscribes',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='user_settings',
        ),
        migrations.AlterModelTable(
            name='usersources',
            table='user_sources',
        ),
        migrations.AlterModelTable(
            name='userusesocialmedia',
            table='user_use_social_media',
        ),
    ]
