# Generated by Django 3.2.9 on 2021-11-30 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetoxLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True, verbose_name='уровень')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('post', models.IntegerField(default=0)),
                ('time', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'verbose_name': 'Уровень детокса',
                'verbose_name_plural': 'Уровни детокса',
                'db_table': 'API_detox_level',
            },
        ),
    ]
