# Generated by Django 3.2.9 on 2021-11-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20211105_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapublic',
            name='name',
        ),
    ]
