# Generated by Django 3.2.9 on 2021-11-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_detoxlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Пользовательская настройка', 'verbose_name_plural': 'Пользовательские настройки'},
        ),
        migrations.AlterModelOptions(
            name='usersources',
            options={'verbose_name': 'Пользовательские ресурсы', 'verbose_name_plural': 'Пользовательские ресурсы'},
        ),
    ]
