# Generated by Django 3.2.9 on 2021-11-19 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0006_auto_20211119_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapublic',
            name='public_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediapublic',
            unique_together={('media', 'public_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subscribes',
            unique_together={('user', 'public')},
        ),
    ]
