# Generated by Django 3.2.9 on 2021-11-20 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0007_auto_20211119_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUseSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Юзер использует социальыне сети',
                'verbose_name_plural': 'Юзеры используют социальыне сети',
                'db_table': 'API_user_use_social_media',
                'unique_together': {('user', 'public')},
            },
        ),
    ]
