# Generated by Django 3.2.9 on 2021-11-20 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0009_auto_20211120_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusesocialmedia',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.socialmedia'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userusesocialmedia',
            unique_together={('user', 'media')},
        ),
    ]
