# Generated by Django 3.2.9 on 2021-11-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20211120_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusesocialmedia',
            name='token',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
